name: Requirements

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - run: make setup

      - name: Generate requirements.txt
        run: make export-requirements > requirements.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update requirements.txt"
          commit_options: "--author 'GitHub Action <action@github.com>'"
