name: Style

on:
  workflow_call:
  push:
    branches: [ max/cpu_tests ]
  pull_request:

jobs:
  base:
    uses: .github/workflows/setup-dev-workflow.yml
  style:
    runs-on: ubuntu-latest
    steps:
      - run: make style