name: Test

on:
  push:
    branches: [ max/cpu_tests ]
  pull_request:

jobs:
  base:
    uses: .github/workflows/setup-dev-workflow.yml
  test:
    needs: base
    runs-on: ubuntu-latest
    steps:
      - run: make test